# Courtesy of https://gist.github.com/azu/673426500458f63f019c8f5e013f282a

name: Tests

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-18.04

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set Windows shell
        if: contains(matrix.os, 'windows')
        run: |
          npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"

      - name: Install, compile and test 
        run: |
          npm install
          npm run compile:electron
          npm run compile:angular
          # npm run test
